export enum ROUTES {
    SIGNIN = "SIGNIN",
    SIGNUP = "SIGNUP",
    MARKET_LIST = "MARKET_LIST",
    ACCOUNT_LIST = "ACCOUNT_LIST"
} 

export enum PRESENTATION_ROUTES {
    LANDING = "LANDING",
    PRESENTATION = "PRESENTATION",
    PRESENTATION2 = "PRESENTATION2",
}

export enum TAB_ROUTES {
    ACCOUNT = "ACCOUNT",
    MARKET = "MARKET"
}

export enum DRAWER_ROUTES {
    LANDING = "LANDING",
    MAIN = "MAIN",
    AUTH = "AUTH",
}

export enum STORAGE_KEYS {
    DONE_PRESENTATION = "DONE_PRESENTATION"
}