export enum ROUTES {
    SIGNIN = "SIGNIN",
    SIGNUP = "SIGNUP",
} 

export enum PRESENTATION_ROUTES {
    LANDING = "LANDING",
    PRESENTATION = "PRESENTATION",
    PRESENTATION2 = "PRESENTATION2",
}


export enum STORAGE_KEYS {
    DONE_PRESENTATION = "DONE_PRESENTATION"
}